version: "3.8"
services:
  mongodb:
    image: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypass
      MONGO_INITDB_DATABASE: solution-station-db
    volumes:
      - data:/data/db
    ports:
      - 27017:27017
    networks:
      - mern-network
  backend:
    build: ./backend
    ports:
      - "80:80"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - mern-network
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-network
networks: #here
    mern-network:
      driver: bridge
volumes:
  data:
  logs:
